# Generated by Django 5.2.9 on 2025-12-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_message_sender_ticket_assigned_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('web', 'Веб-портал'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('api', 'API')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Конфигурация канала (токены, webhook URL и т.д.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Канал коммуникации',
                'verbose_name_plural': 'Каналы коммуникации',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='channel',
            field=models.CharField(choices=[('web', 'Веб-портал'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('api', 'API')], default='web', help_text='Канал, через который поступило обращение', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID обращения во внешней системе (email message-id, telegram chat_id и т.д.)', max_length=255, null=True),
        ),
    ]
