# Generated by Django 5.2.9 on 2025-12-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_channel_ticket_channel_ticket_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Helpful'), (-1, 'Not Helpful')], help_text='Оценка ответа AI: 1 = полезно, -1 = не полезно', null=True),
        ),
    ]
