# Generated by Django 5.2.9 on 2025-12-05 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_message_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержание (Markdown)')),
                ('summary', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('internet', 'Internet'), ('tv', 'TV'), ('billing', 'Billing'), ('other', 'Other')], default='other', max_length=20, verbose_name='Категория')),
                ('tags', models.CharField(blank=True, help_text='Теги через запятую: роутер, интернет, настройка', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Полезно')),
                ('not_helpful_count', models.IntegerField(default=0, verbose_name='Не полезно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('source_ticket', models.ForeignKey(blank=True, help_text='Тикет, из которого создана статья', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Статья базы знаний',
                'verbose_name_plural': 'База знаний',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='tickets_kno_status_8294cb_idx'), models.Index(fields=['category'], name='tickets_kno_categor_7df141_idx')],
            },
        ),
    ]
